### ISSUE TITLE
Size of Shard 0 DB Snapshot Seems Too BIG

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#183] opened 2019-10-20 23:29 UTC
The size of the DB snapshot for shard 0 is over bigger than it should be, while the size for other shards looks fine. See the attached screenshots.

<img width="699" alt="Screen Shot 2019-10-20 at 4 27 40 PM" src="https://user-images.githubusercontent.com/5258417/67168209-ce932e80-f356-11e9-98d8-0c94d3f55e68.png">
<img width="704" alt="Screen Shot 2019-10-20 at 4 27 25 PM" src="https://user-images.githubusercontent.com/5258417/67168210-ce932e80-f356-11e9-89ec-f4e7267653c4.png">
<img width="703" alt="Screen Shot 2019-10-20 at 4 27 08 PM" src="https://user-images.githubusercontent.com/5258417/67168211-ce932e80-f356-11e9-844d-4785df0d7a7e.png">
<img width="1261" alt="Screen Shot 2019-10-20 at 4 02 30 PM" src="https://user-images.githubusercontent.com/5258417/67168212-ce932e80-f356-11e9-8bdd-5a1ddc666452.png">

**Comment by LeoHChen** [comment] 2019-10-21 05:39
```
$ aws s3 ls pub.harmony.one/mainnet/harmony_db_0/ > 0.log
$ wc -l 0.log
58839 0.log
```
You can see there are 58839 files in harmony_db_0 folder

login to sentry 0
```
[ec2-user@ip-172-31-0-34 ~]$ ls -al harmony_db_0/ | wc -l
20553
```

I suggest to remove harmony_db_0 folder on the pub.harmony.one bucket, and redo the rclone from sentry 0 node.

**Comment by LeoHChen** [comment] 2019-10-21 09:23
I've fixed it, removed the harmony_db_0 on the bucket. The root cause I think was I setup two cronjob to sync the db_0 from two nodes to the public bucket.  I disabled one of them and it should be fixed now.  Please double check it.

**Closed** 2019-10-23 21:36 UTC
