### ISSUE TITLE
Nodedb Script scanns and Keeps the new Explorer in the List of IP

### ISSUE THREAD

**Issue by AndyBoWu** [harmony-one/harmony-ops#343] opened 2020-01-21 21:16 UTC
the previous explorer didn't get added into the the ip file for some reason.

**Comment by LeoHChen** [comment] 2020-01-22 07:05
found the root cause. nodedb.sh assumes one explorer node per shard.

![image](https://user-images.githubusercontent.com/4513927/72872585-90354480-3ca2-11ea-9769-a9303fdddcdb.png)

**Comment by LeoHChen** [comment] 2020-01-22 07:48
fixed in https://github.com/harmony-one/nodedb/commit/c990cd26a5d0d4006bf8d568f0c7f01ead2de848

**Closed by LeoHChen** 2020-01-22 07:48 UTC
