### ISSUE TITLE
Testnets by p-ops

### ISSUE THREAD

**Issue by mindstyle85** [harmony-one/harmony-ops#588] opened 2020-06-15 22:49 UTC
We need to set out a plan on how to run the testnets, I believe we have regular internal nodes, explorer, dns and boot nodes to run here.

Prereq:

- access to DO account that has credits (@NiteeshHarmony )
- access to bls/node deploy scripts
- ansible automation for deployment
- explorer
- get Seb to work with us on this at the start (with him we will be the fastest and probably most polished auto deploy solution)
- does team need access too?
- possible easier debug/log search system in the future?
- rolling upgrade procedure

-additional (STN?): CI pipeline setup on our main repo so that every PR can be built/tested on a small network + quick regression tests (within 5min)

@sophoah will take point on this one as he is the most skilled of us and already made our ansible automation for our validator. We can add more to this ticket below.

**Comment by LeoHChen** [comment] 2020-06-15 23:36
# Requirement on the testnets #

We need to maintain **two** testnets.

## LRTN ##
One is a stable long running network, should run the same version as mainnet's current release.
The users of this testnet is for dApp developers and partners.
They can deploy smart contracts on any of the 4 shards.
The db snapshots have to be kept and archived like every day.
The uptime of this network has to be 99%, including explorer/staking dashboard/rpc end points.

## STN ##
This testnet is an ad-hoc network, will be launched/terminated every night or per PR basis.
The users of this testnet are Harmony protocol developers, both internal and external.
We shall keep regression test running on this testnet all the time.  Per PR tests are regression/minimal.
Nightly tests are stress test and longer regression test.
The DB on this network is not guaranteed to be kept, but we should try to maintain it for long running.
The uptime of this network is 95%, including explorer/staking dashboard/rpc end points.

**Comment by JB273** [comment] 2020-06-16 08:40
Regarding this point:
- possible easier debug/log search system in the future

Got confirmation from Yishuan that we can use ElasticSearch for this.

**Comment by yelllowsin** [comment] 2020-06-16 12:52
Thanks guys for starting this. I few comments/considerations by my side:

- I'd suggest we start with LRTN and leave STN for later. First, because LRTN will be a long run testnet like the name says, so we should not have events of a network deployed from scratch like it would probably happen with STN. This will give us room to understand it better for later deployments of STN. Also we will have time to understand it better and improve/review the docs in the meantime.

- Where is LRTN currently running @LeoHChen? I personally like DO due to it's low costs and i think it fits our needs. They have datacenters in 3 regions, US/Canada, Europe and Asia, so we can distribute nodes around the globe with high uptime in the long term. We would need to check with @NiteeshHarmony about the credits, because differently from AWS, they "usually" don't charge for bandwith usage, instead they have a quota of a few Terabytes per node which is enough to run for the whole month. Need to check though if the same rules are valid if we deploy there using our existing credits.

- @JB273 i like Elastic Search, we have used it already with our harmony nodes and it works nicely. We can definetely use it to monitor logs on LRTN

**Comment by sophoah** [comment] 2020-06-16 14:51
@LeoHChen can you talk a bit more on how do you expect the update to be pushed.  Automatically fetched via node.sh on the latest binary for LRTN ? a restart that fetch the latest binary? (similar to mainnet external node currently), or via a build process that would do the deployment via jenkins? 

I'll be studying for the next few days the ansible playbook and the devops documentation. I'll surely ask more question. Thanks

**Comment by LeoHChen** [comment] 2020-08-13 07:04
testnet fully transferred to p-ops, closing this ticket.

**Closed by LeoHChen** 2020-08-13 07:04 UTC
Labels: help wanted
